### ISSUE TITLE
[connector] implement predicate, projection, join, aggregation, and limit pushdown.

### ISSUE THREAD

**Issue by bianhq** [pixelsdb/pixels-trino#4]
Trino's optimizer supports the pushdown of many complex operators, such as join and aggregation.
This is interesting to us.

**Comment by anonymous20221015** [comment]
Limit pushdown is currently not needed, other kinds of pushdown are implemented.

**Comment by bianhq** [comment]
Limit pushdown is currently not needed, other kinds of pushdown are implemented.
